namespace Enum;

public enum State
{
    WAITING_FOR_PLAYER,
    BOTH_CHOOSING_CARDS,
    PLAYER_ONE_CHOOSING_CARDS,
    PLAYER_TWO_CHOOSING_CARDS,
    BOTH_CHOOSING_GAME_CARD,
    PLAYER_ONE_CHOOSING_GAME_CARD,
    PLAYER_TWO_CHOOSING_GAME_CARD,
    PLAYER_ONE_TURN,
    PLAYER_TWO_TURN,
    PLAYER_ONE_WAITING_FOR_REPLY,
    PLAYER_TWO_WAITING_FOR_REPLY,
}
