// <auto-generated />
using System;
using Backend.Features.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RaptorProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241125154325_BE-Refactor")]
    partial class BERefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Features.Board.BoardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("ChosenCardID")
                        .HasColumnType("integer");

                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersLeft")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ChosenCardID");

                    b.HasIndex("GameID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("Backend.Features.BoardCard.BoardCardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("BoardID")
                        .HasColumnType("integer");

                    b.Property<int>("CardID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BoardID");

                    b.HasIndex("CardID");

                    b.ToTable("BoardCard");
                });

            modelBuilder.Entity("Backend.Features.Card.CardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("Backend.Features.Game.GameEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("GameState")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerOneID")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerTwoID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PlayerOneID");

                    b.HasIndex("PlayerTwoID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Backend.Features.Message.MessageEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("BoardEntityID")
                        .HasColumnType("integer");

                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<string>("MessageText")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BoardEntityID");

                    b.HasIndex("GameID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Backend.Features.Player.PlayerEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Backend.Features.Board.BoardEntity", b =>
                {
                    b.HasOne("Backend.Features.BoardCard.BoardCardEntity", "ChosenCard")
                        .WithMany()
                        .HasForeignKey("ChosenCardID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Features.Game.GameEntity", "Game")
                        .WithMany("Boards")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Features.Player.PlayerEntity", "Player")
                        .WithMany("Boards")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenCard");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Backend.Features.BoardCard.BoardCardEntity", b =>
                {
                    b.HasOne("Backend.Features.Board.BoardEntity", "Board")
                        .WithMany("BoardCards")
                        .HasForeignKey("BoardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Features.Card.CardEntity", "Card")
                        .WithMany("BoardCards")
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Backend.Features.Card.CardEntity", b =>
                {
                    b.HasOne("Backend.Features.Player.PlayerEntity", "Player")
                        .WithMany("Cards")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Backend.Features.Game.GameEntity", b =>
                {
                    b.HasOne("Backend.Features.Player.PlayerEntity", "PlayerOne")
                        .WithMany("GamesAsPlayerOne")
                        .HasForeignKey("PlayerOneID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Features.Player.PlayerEntity", "PlayerTwo")
                        .WithMany("GamesAsPlayerTwo")
                        .HasForeignKey("PlayerTwoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PlayerOne");

                    b.Navigation("PlayerTwo");
                });

            modelBuilder.Entity("Backend.Features.Message.MessageEntity", b =>
                {
                    b.HasOne("Backend.Features.Board.BoardEntity", null)
                        .WithMany("Messages")
                        .HasForeignKey("BoardEntityID");

                    b.HasOne("Backend.Features.Game.GameEntity", "Game")
                        .WithMany("Messages")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Features.Player.PlayerEntity", "Player")
                        .WithMany("Messages")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Backend.Features.Board.BoardEntity", b =>
                {
                    b.Navigation("BoardCards");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Backend.Features.Card.CardEntity", b =>
                {
                    b.Navigation("BoardCards");
                });

            modelBuilder.Entity("Backend.Features.Game.GameEntity", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Backend.Features.Player.PlayerEntity", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Cards");

                    b.Navigation("GamesAsPlayerOne");

                    b.Navigation("GamesAsPlayerTwo");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
